import type { Metadata } from "next";

import "./globals.css";
import Providers from "./providers";
import { Navbar } from "@/components/Navbar";
import { nohemi } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Scribblr - AI Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning  className={`${nohemi.variable} h-full antialiased` }>
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
